// ─── Map Style Arrays ────────────────────────────────────────────────────────

const MAP_LIGHT = [
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
];

const MAP_DARK = [
  { elementType: 'geometry', stylers: [{ color: '#242f3e' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#242f3e' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#746855' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#d59563' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#38414e' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#212a37' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#9ca5b3' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#746855' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#1f2835' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#f3d19c' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#2f3948' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#17263c' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#515c6d' }] },
];

const MAP_NORD = [
  { elementType: 'geometry', stylers: [{ color: '#2e3440' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#2e3440' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#d8dee9' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#434c5e' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#3b4252' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#e5e9f0' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#5e81ac' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#88c0d0' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#1c2333' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#4c566a' }] },
];

const MAP_DRACULA = [
  { elementType: 'geometry', stylers: [{ color: '#282a36' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#21222c' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#f8f8f2' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#44475a' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#f8f8f2' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#6272a4' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#bd93f9' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#1a1a2e' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#6272a4' }] },
];

const MAP_GRUVBOX = [
  { elementType: 'geometry', stylers: [{ color: '#282828' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1d2021' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#ebdbb2' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#3c3836' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#a89984' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#504945' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#fe8019' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#076678' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#458588' }] },
];

const MAP_SOLARIZED = [
  { elementType: 'geometry', stylers: [{ color: '#002b36' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#001f27' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#657b83' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#073642' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#839496' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#0d4a5a' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#268bd2' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#001f27' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#2aa198' }] },
];

const MAP_MIDNIGHT = [
  { elementType: 'geometry', stylers: [{ color: '#000000' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#000000' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#111111' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#8e8e93' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#1c1c1e' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#0a84ff' }] },
  { featureType: 'transit', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#000814' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#636366' }] },
];

// ─── Theme Definitions ────────────────────────────────────────────────────────

export const THEMES = {
  daylight: {
    key: 'daylight',
    name: 'Daylight',
    emoji: '☀️',
    dark: false,
    colors: {
      bg: '#F5F7FA',
      surface: '#FFFFFF',
      border: '#E8ECF0',
      text: '#1A1A1A',
      textSub: '#6B7B9A',
      textMuted: '#9CA3AF',
      primary: '#007AFF',
      primaryLight: '#E6F0FF',
      inputBg: '#F5F7FA',
      tabBg: '#FFFFFF',
      handle: '#CBD5E1',
      danger: '#FF3B30',
      warning: '#FFCC00',
      success: '#34C759',
    },
    mapStyle: MAP_LIGHT,
  },

  obsidian: {
    key: 'obsidian',
    name: 'Obsidian',
    emoji: '🌑',
    dark: true,
    colors: {
      bg: '#1E1E2E',
      surface: '#2A2A3E',
      border: '#45475A',
      text: '#CDD6F4',
      textSub: '#A6ADC8',
      textMuted: '#6C7086',
      primary: '#CBA6F7',
      primaryLight: '#2A1F3D',
      inputBg: '#313244',
      tabBg: '#181825',
      handle: '#585B70',
      danger: '#F38BA8',
      warning: '#F9E2AF',
      success: '#A6E3A1',
    },
    mapStyle: MAP_DARK,
  },

  nord: {
    key: 'nord',
    name: 'Nord',
    emoji: '❄️',
    dark: true,
    colors: {
      bg: '#2E3440',
      surface: '#3B4252',
      border: '#434C5E',
      text: '#ECEFF4',
      textSub: '#D8DEE9',
      textMuted: '#616E88',
      primary: '#88C0D0',
      primaryLight: '#2D3B47',
      inputBg: '#4C566A',
      tabBg: '#242933',
      handle: '#4C566A',
      danger: '#BF616A',
      warning: '#EBCB8B',
      success: '#A3BE8C',
    },
    mapStyle: MAP_NORD,
  },

  dracula: {
    key: 'dracula',
    name: 'Dracula',
    emoji: '🧛',
    dark: true,
    colors: {
      bg: '#282A36',
      surface: '#343746',
      border: '#44475A',
      text: '#F8F8F2',
      textSub: '#8BE9FD',
      textMuted: '#6272A4',
      primary: '#BD93F9',
      primaryLight: '#3A2D52',
      inputBg: '#44475A',
      tabBg: '#21222C',
      handle: '#6272A4',
      danger: '#FF5555',
      warning: '#F1FA8C',
      success: '#50FA7B',
    },
    mapStyle: MAP_DRACULA,
  },

  gruvbox: {
    key: 'gruvbox',
    name: 'Gruvbox',
    emoji: '🪵',
    dark: true,
    colors: {
      bg: '#282828',
      surface: '#3C3836',
      border: '#504945',
      text: '#EBDBB2',
      textSub: '#A89984',
      textMuted: '#7C6F64',
      primary: '#FE8019',
      primaryLight: '#3D2B1A',
      inputBg: '#32302F',
      tabBg: '#1D2021',
      handle: '#504945',
      danger: '#CC241D',
      warning: '#D79921',
      success: '#98971A',
    },
    mapStyle: MAP_GRUVBOX,
  },

  things: {
    key: 'things',
    name: 'Things',
    emoji: '🌿',
    dark: false,
    colors: {
      bg: '#FAF8F5',
      surface: '#FFFFFF',
      border: '#EDE8E1',
      text: '#2C2C2C',
      textSub: '#8A7F72',
      textMuted: '#B5AEA4',
      primary: '#E07B39',
      primaryLight: '#FDF0E6',
      inputBg: '#F5F1EA',
      tabBg: '#FFFFFF',
      handle: '#D6D0C8',
      danger: '#E53935',
      warning: '#F59E0B',
      success: '#4CAF50',
    },
    mapStyle: MAP_LIGHT,
  },

  solarized: {
    key: 'solarized',
    name: 'Solarized',
    emoji: '🌊',
    dark: true,
    colors: {
      bg: '#002B36',
      surface: '#073642',
      border: '#0D4A5A',
      text: '#839496',
      textSub: '#657B83',
      textMuted: '#586E75',
      primary: '#268BD2',
      primaryLight: '#0A2A36',
      inputBg: '#073642',
      tabBg: '#001F27',
      handle: '#2D5A6A',
      danger: '#DC322F',
      warning: '#B58900',
      success: '#859900',
    },
    mapStyle: MAP_SOLARIZED,
  },

  midnight: {
    key: 'midnight',
    name: 'Midnight',
    emoji: '🌃',
    dark: true,
    colors: {
      bg: '#000000',
      surface: '#111111',
      border: '#222222',
      text: '#FFFFFF',
      textSub: '#8E8E93',
      textMuted: '#636366',
      primary: '#0A84FF',
      primaryLight: '#001933',
      inputBg: '#1A1A1A',
      tabBg: '#000000',
      handle: '#3A3A3C',
      danger: '#FF453A',
      warning: '#FFD60A',
      success: '#30D158',
    },
    mapStyle: MAP_MIDNIGHT,
  },
};

export const THEME_KEYS = Object.keys(THEMES);
